spectator final decision UI
ECE493G14Capstone/Capstone pull request #83
Opened 2022-03-29 17:05 UTC by AdityaHarvi

2022-03-30 14:50 UTC, swebra requested changes
Just to keep SceneGameArena focused primarily on the main gameplay stuff I'd maybe abstract this out into its own UI class like the controlsUI? Though I get why you didn't because its so small. idk, use your best judgement.

2022-03-30 14:50 UTC, swebra commented on client/src/scene/SceneGameArena.ts
> +            .setVisible(false);
I don't see this being set true anywhere and I don't think we need it... I thought we'd always have something showing with the default text being something like "None"

2022-03-30 20:43 UTC, AdityaHarvi commented
I'll leave it up to @swebra to finish off the positioning of the text with the new background img (or I can take it on as well, if you wanted to push that change first)

2022-03-31 21:32 UTC, swebra commented
Closing this PR and its branch in favor of #87 which includes the changes.

2022-03-31 21:32 UTC, closed without merging